[project]
name = "mcp-postgres"
version = "0.1.0"
description = "MCP PostgreSQL服务"
readme = "README.md"
dependencies = [
      "mcp>=1.2.1",
      "psycopg2-binary>=2.9.10",
      "python-dotenv>=1.0.1",
]
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mcp-postgres = "mcp_postgres:main"
