name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: false
      
      - name: Set up Python
        run: uv python install
      
      - name: Install build dependencies
        run: uv sync --all-extras
      
      - name: Build package
        run: uv build
      
      - name: Publish to PyPI
        run: uv publish
